kufu/textlint-rule-preset-smarthr

dict/prh-basic.yml
『上側に』『下側に』『左側に』『右側に』『内側に』『外側に』などが誤判定しないようにしました。
=> 『[上下左右内外]側[にへが]』が誤判定しないように

src/@type/@textlint/module-interop.d.ts, src/@type/@textlint/require.d.ts
https://smarthr.atlassian.net/browse/SD-361
`@textlint/module-interop`と`require`の型が未定義なので、
エディタ上でサジェストが表示されてしまうのでなんとかしたい。
`@textlint/module-interop`と`require`の型定義ファイルを暫定的に追加。
エディタ上（VScode推奨）で型未定義のサジェストが表示されないこと。
=> refactor: TypeScriptのtypeを追加

src/@type/@textlint/require.d.ts
すみません、[これ](https://github.com/kufu/textlint-rule-preset-smarthr/pull/5)をマージすることで、requireが重複し、`Duplicate identifier`を引き起こしてました。
お手数をおかけしますが再度ご確認をお願いします:pray:
型定義require.d.tsを削除しました。
`yarn build`でエラーが起きないこと。
=> fix: require.d.tsの削除

dict/prh-tech-word.yml
prh-tech-word から `LINE` を削除した。
TypeScriptなどのコードを解析する場合、文言以外の string も対象になるが、`line` は変数名で頻出するためコードが書き換えられてしまうため。
例: `FaChartLine` from SmartHR UI - Icon https://github.com/kufu/smarthr-ui/blob/master/src/components/Icon/Icon.tsx#L67
=> Remove LINE from prh tech word

CHANGELOG.md
- v1.4.0の更新内容の一部がCHANGELOG.mdに記述されていなかったので修正更新したい
- CHANGELOGの更新漏れを対応
=> fix: CHANGELOGの更新漏れ対応

renovate.json
- https://smarthr.atlassian.net/browse/TEXTLINT-47
- 互いに依存関係のあるライブラリアップデートのPRが個別に作られるとCI通らなかったりしてつらい
- そうでなくてもrule系が一気にアップデートきて、1つマージするたびにrebaseするのもつらい
- 互いに依存度が強いライブラリアップデートを1つのPRにまとめるようにした
- textlint-rule-* のルール関連
- textlint本体絡み
🍐
1. ✅ 以下コマンドで `renovate.json` がvalidなことを確認する
```sh
$ npx --package renovate -c 'renovate-config-validator'
```
=> chore: renovateで依存度が強いパッケージをグループ化してconflictを抑える TEXTLINT-47

.github/workflows/release.yml, .github/workflows/test.yml, .releaserc.json, commitlint.config.js, package.json, yarn.lock
- https://smarthr.atlassian.net/browse/TEXTLINT-63
- 現在リリース作業が属人化しており、リリースできる人が限られる
- リリース作業に割くリソースも安定して確保できないので、負荷を極力減らしたい
- 自動Releaseを実行するために[semantic-release](https://github.com/semantic-release/semantic-release)を追加
- 設定は[textlint-rule-preset-bengo4](https://github.com/bengo4/textlint-rule-preset-bengo4)を参考としています。
- Github ActionのTest名を`Test`に修正
- Github Actionに`Release`を追加
- `commitlint.config`に`body-max-line-length`の設定を追加
- CHANGELOGの更新の際、長文が入ったときにlintエラーが走ったのでその対応として追加してます。
- `secrets`にnpmjs.comへの公開用`npm token（Automation）`を設定 
- PRタイトルのlint用に`Title lint`Appを設定
- https://github.com/apps/title-lint
- リポジトリのSetting周りを確認する
- Testが通るかチェックする
- （注意）PRを通すとReleaseが走るはずなので、事前の同期的チェックと確認は必須
=> feat: 自動リリース機能の追加

.github/workflows/release.yml
- semantic-release経由でrelease作業を実行しようとすると、branchへの権限不足でエラーが起きてしまう
- ![CleanShot 2021-08-31 at 20 59 08](https://user-images.githubusercontent.com/4032232/131498687-9a71463a-a214-4f25-9410-93e6e6cd4fa4.png)
- https://github.com/kufu/textlint-rule-preset-smarthr/runs/3472399376?check_suite_focus=true
- 最終的にこの設定で解決できそうなことを発見
- https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/github-actions.md#pushing-packagejson-changes-to-a-master-branch
- ~https://github.com/semantic-release/github/issues/175#issuecomment-757448750 を参照。~
- ~Brunch Protectionがかかっている場合、自動生成される`GITHUB_TOKEN `ではなく、Personal Tokenとして発行したtokenを`GH_TOKEN`として設定すれば動作する...と言ったことが書いていた。~
- これは個人のtokenを使うことになるため、望ましくなさそうということで却下
- `actions/checkout@v2`に対して`persist-credentials: false`の設定を追加した。
- 参考記事
- …
=> fix: branch protectionによってsemantic-releaseが失敗する問題を解決する

.github/workflows/release.yml
https://github.com/kufu/textlint-rule-preset-smarthr/pull/96 でも設定不足でreleaseができなかったので、修正したい
- semantic-release用のgithubのtokenを設定してみた
- 管理者のtokenを使ってるので、管理者変更の際はtokenを差し替えることが必須
- 参考
- https://github.com/semantic-release/github/issues/175#issuecomment-757448750
=> fix: release actionにtokenを追加

.github/titleLint.yml
https://smarthr.atlassian.net/browse/TEXTLINT-65
renovateのPRがtitleLintに怒られているので、renovateからのPRは無視したい。
- `.github/titleLint.yml` を追加
- カッコ書きを許容するregexを指定
- exclude_usersにrenovateを指定
🍐 
renovateによる `chore(deps): hoge` のようなタイトルのPRが通ればOK
https://github.com/kufu/textlint-rule-preset-smarthr/pull/94
これとか
=> chore: titleLintでrenovateを無視する設定を追加

README.md, example/.textlintrc, package.json, yarn.lock
https://smarthr.atlassian.net/browse/TEXTLINT-68
hiragana-keishikimeishiのアップデートに合わせて、以下を変更
- README.md
- example/.textlintrc
- package.json
- yarn.lock
=> fix: hiragana-keishikimeishiのアップデートに対応

dict/prh-basic.yml
「様」を「さま」に変換する正規表現が間違っていた。
- 正規表現の修正
なし
- お客様
- お客さま
=> fix: 様→さま の正規表現が間違っていたので修正

package.json, test/.textlintrc
テストを行う際には `dict/*.yml` の定義中に含まれる `specs` の中身も検証したい。
- `test:dict` というコマンドを追加した。中では textlint を実行しており、specs のチェックが行われる。
- これまでやっていた `test`  というコマンドは `test:textlint-scripts` に変更した。
- `test` では `test:textlint-scripts`、`test:dict` を逐次実行するようにした。
- `test` を呼び出した際、`test:textlint-scripts`、`test:dict` を並列実行することも検討したが、1〜3秒くらいしか実行時間が短縮できなかったのでやめた。
- `npm test` （あるいは `npm run test:dict`）が実行でき、正常終了すること
- `dict/prh-basic.yml` の定義に適当な specs を追加し、`npm test` （あるいは `npm run test:dict`）を実行すると失敗すること
=> feat: npm test 実行時、定義中に含まれる spec の内容を検証

.github/workflows/titleCheck.yml
- `standard-version`で正しくアップデートさせるため、PRタイトルのlintを実行したい
- Github ActionにPR Titleのlintを実行する処理を追加
- https://github.com/kufu/smarthr-ui/pull/1925を参考としています。
=> chore: プルリクエストタイトルのlintを追加

dict/fukushi.yml, src/index.ts, test/cases/pass.js
`正しく` という文字を `まさしく` と表現させるlintがあるが、この文言はそのまま利用できるのが正しいので誤検知を修正した。
- `lostandfound/textlint-rule-ja-hiragana-fukushi` の辞書ymlをコピーしてリポジトリに追加した
- リポジトリに追加したのち、 `正しく` に関するルールを削除した
- テストを追加して、誤検知されている内容が修正後にpassすることを検証できるようにした
- 本家へのPR。個別最適していけばいいと思うので、本家へPRは不要と判断した。
`正しく値を返す。` この文言が誤検知されないこと。
=> fix: 「正しく」を誤検知しない

package.json
follow up https://github.com/kufu/textlint-rule-preset-smarthr/pull/142
dict配下のファイルがpackage対象外になっていたため、publishされたpackage内部にymlファイルが存在しない状態になっている
dictをpackageの対象に含めた
=> fix: add dict directory

dict/prh-idiomatic-usage.yml
meyasu で `textlint-rule-preset-smarthr` の1.13.2 対応で「行う」を「行なう」に修正している際に、「行なわれる」が検知できていないことに気づきました。
https://github.com/kufu/meyasu/pull/2384#discussion_r879328266
該当の文言
- ` まだ回答依頼は行われていません。 `
もともとのルール追加は以下のPRで行なわれていそうです
- https://github.com/kufu/textlint-rule-preset-smarthr/pull/194
「行われる」「おこなわれる」が検知され、「行なわれる」に修正されるようにルールを修正しました。
- まだ回答依頼は**行なわ**れていません。
- まだ回答依頼は**おこなわ**れていません。
- まだ回答依頼は**行わ**れていません。
=> fix: 「行なわれる」を検知できるようにする

dict/prh-idiomatic-usage.yml
https://smarthr.design/products/writing/idiomatic-usage/usage/ が404エラーとなるため 変更したい。 
https://smarthr.design/products/contents/writing-style/  は見れるようなのでそちらにしました。
現在は https://smarthr.design/products/contents/writing-style/#recWCPX1UhchVaFjO-0 ですが、
ハッシュ  `#recWCPX1UhchVaFjO-0` は不定な気がするのでURLに含めていません
=> fix: 「平仮名にしたほうが読みやすい漢字は平仮名にする」に併記されているURLのアップデート 

README.md, example/.textlintrc, package.json
ja-keishikimeishiが1.0.4にバージョンアップし、「上（うえ）」の判定をフラグで制御できるようになったので、追従したい。
また、デフォルトは `false` にしておきたい。
- package.json の更新
- .textlintrc の更新
- README.md の更新
確認のうえ、作業します。
確認の上、作業します。
=> feat: ja-keishikimeishiのバージョン1.0.4に対応＆オプション追加

yarn.lock
- yarn install すると yarn.lock に差分が生じてリリースに失敗するので更新したい！
- `$ yarn install` して発生した yarn.lock の差分をコミットしたよ
ないヨ
- CIがテストが通っていれば大丈夫そう〜
変更ナシ！
変更ナシ！
=> chore(deps): yarn installするとyarn.lockに差分が生じるので更新したい

dict/prh-tech-word.yml
ガイドラインで[「ウェブ」はカタカナで表記する](https://smarthr.design/products/contents/idiomatic-usage/usage/#rec8ZIzDZQ47CFM5l-0)と決めたが、Web表記を正とするルールが残っていたので削除したい。
`prh-tech-word.yml` から該当部分を削除
その他の変更
ウェブサイト
Webサイト
=> fix: 「ウェブ→Web」のルールを削除

README.md
textlint-tester URL has changed
before:
https://github.com/textlint/textlint-tester
after:
https://github.com/textlint/textlint/tree/master/packages/textlint-tester
=> fix(README): textlint-tester URL has changed

dict/prh-idiomatic-usage.yml, dict/prh-tech-word.yml
デザインシステム内で、textlintの誤検知が理由でルールを無視せざるを得ない箇所があったため、ルールを修正したい。
- ユーザビリティ→ユーザービリティ の誤検知を修正
- 「ユーザ」の後が「ビリティ」の場合は検知しない
- フィルタリング→フィルターリング の誤検知を修正
- 「フィルタ」の後が「リング」の場合は検知しない
- 利用者側、依頼側→利用者そば、依頼そばの誤検知を修正
- 「側」の前が漢字の場合は検知しない
=> fix: デザインシステム内の誤検知を解消

scripts/export-airtable-rules.ts
Airtable APIのレコード取得上限の100件よりもルールが多くなり、一部のルールが取得できなくなっていたので、修正したい。
https://support.airtable.com/docs/api-record-limits
- `records`取得部分のコードを修正
- それ以外のコードの修正
- GitHub Actionsでbranchに`fix-airtable-records-limit`を指定して、ルールを全件取得できていることを確認済み。
=> fix: 101件以上のレコードを取得できるように修正

dict/prh-idiomatic-usage.yml
以前対応した「マスター」の誤検知が直っていなかったので修正したい。
https://kufuinc.slack.com/archives/C01RP2QJT2B/p1672964973922399?thread_ts=1670549531.752129&cid=C01RP2QJT2B
rubyの正規表現エンジンでも誤検知が起こらないように正規表現を書き換えた。
=> fix: 「マスター」のルールを修正

dict/prh-idiomatic-usage.yml
「ならび→並び」のルールが「並びに→ならびに」のルールとコンフリクトしていたので、修正。
「ならびに」を検知しないよう修正した。
=> fix: 「ならび」の誤検知を修正

dict/prh-idiomatic-usage.yml
↓に対応もれがあったので追加で修正しました 🙏 
https://kufuinc.slack.com/archives/C01RP2QJT2B/p1673927110936349?thread_ts=1673920541.442159&cid=C01RP2QJT2B
「横並びに」「縦並びに」を「ならびに」で誤検知しないよう修正。
「横ならびに」「縦ならびに」が検知されない問題は別チケ対応。
https://smarthr.atlassian.net/browse/TEXTLINT-111
=> fix: 「横並びに」「縦並びに」を誤検知しないように修正

dict/prh-idiomatic-usage.yml
https://smarthr.atlassian.net/browse/TEXTLINT-113
- 「一人ひとり」「一人称」を「1人1人」「1人称」に誤検知しないよう修正
=> fix: 「一人ひとり」「一人称」の誤検知を修正

dict/prh-idiomatic-usage.yml
- 「ひとり親」が「1人親」に誤検知されていたため、修正する
- 「ひとり」の正規表現を修正
=> fix: 「ひとり親」の誤検知を修正

dict/prh-idiomatic-usage.yml
base64エンコード後の画像データに含まれる「PC」の文字列を誤検知していたため、修正したい。
- PCの前後にアルファベットがある場合は、検知しないようにルールを修正
- 用字用語のNG例にない「パーソナルコンピューター」のルールを削除
=> fix: PCの誤検知を修正

dict/prh-idiomatic-usage.yml
「解す→ほぐす」のルールが「読解する」で誤検知していたため、修正したい。
https://kufuinc.slack.com/archives/C018J0A6DCH/p1680234560272669
「読解する」を検知しないようルールを修正した。
=> fix: 「解す」の誤検知を修正

package.json
- v13からtextlint-testerの依存パッケージ群からtextlintが外れたため、テストが落ちるようになった
- devDependenciesにtextlintを追加し、テストが落ちないようにしたい
- devDependenciesにtextlintを追加
=> fix: devDependenciesにtextlintを追加

.github/workflows/startRelease.yml
リポジトリのnodeバージョンにワークフローのnodeバージョンを合わせたい。
ワークフローによるリリースができないため。
ワークフローのnodeバージョンを上げた。
=> fix: リリース用ワークフローで使用するNodeのバージョンを14→16にアプデ

.github/workflows/publishRelease.yml
リポジトリのnodeバージョンにワークフローのnodeバージョンを合わせたい。
ワークフローによるpublishができないため。
`publishRelease.yml` のnodeバージョンを上げた。
=> fix: publesh_releaseワークフローで使用するNodeのバージョンを14→16にアプデ

.github/workflows/publishRelease.yml, .github/workflows/startRelease.yml, .github/workflows/test.yml
依存パッケージアップデートでテストにnode 18以上が必要になったため。
GItHub Actionsのymlで指定しているnodeのバージョンを16から18に変更した。
=> chore: update GitHub Actions node version to 18

dict/prh-idiomatic-usage.yml
textlint-rule-preset-smarthrを利用している、サービスサイトの独自辞書を作成中に、こちらに追加したほうが良いと判断したものを追加
- 文書配付
- シミュレーション
- 「有り」に関するルールはあったけれど、「無し」に関するルールがなかった
- 「かかわらず」のPatternに「係わらず」がなかった
- 「頂く」のルールしかなかったので、活用形を追加
- ルールの追加
ない
なければ
かかわらず
無い
無ければ
係わらず
=> feat: 文書配付、シミュレーション、係わらずと無い、頂くの活用を追加

dict/prh-idiomatic-usage.yml
ボタンを押下する操作に対する「押下する」の表現がガイドラインで禁止されているので、textlintで検出できるようにしたい。
https://smarthr.design/products/contents/idiomatic-usage/usage/#recVAeJr4Di3vQHeA-0
> アプリケーション上でボタンを押下する操作は「押す」と表現し、「クリック」「タップ」「押下」の使用は控える
依頼元：https://kufuinc.slack.com/archives/CJX59GJFR/p1718155653977809
Jira Ticket：https://smarthr.atlassian.net/browse/SD-808
以下のようにBefore&Afterのバリュエーションが多く、正規表現での置換は困難。
- 押下する → 押す
- 押下します → 押します
- 押下しない → 押さない
- 押下できる/できない → 押せる/押せない
- 押下すれば → 押せば
- 押下したら → 押したら
置換それぞれを1つずつルールとして（＝Airtableの行として）定義する方針もありとのことで、その方針とする。 https://kufuinc.slack.com/archives/CJX59GJFR/p1718679042992979?thread_ts=1718155653.977809&cid=CJX59GJFR
追加したレコード
https://airtable.com/appgRe6XLv39vNM0C/tblbDiUxsSKGMXn0j/viwmiJfdPnu1duaMv/recUSfsOANhHlu05c?blocks=hide …
=> feat: 「押下する」を禁止する

.github/workflows/publishRelease.yml
* kufu orgで共用できるnpm tokenが発行されたので入れ替える
* npm publish時に参照するtokenを入れ替え
* 従来のtokenをGitHubのsecretsから削除する
=> chore: npm publish用のトークン入れ替え

.github/workflows/publishRelease.yml
- ~GitHub Actionsで `pnpm publish` を実行する際、`--no-git-checks` を指定しないと、npmへの公開に失敗する~
- ~publishするブランチがmain/master以外の場合は指定しないといけない~
- main/masterブランチ以外で `pnpm publish` を実行する際、ブランチを明示しないとエラーが発生する
- `pnpm publish` に `--publish-branch release-candidate` を追加
=> fix: pnpm publish時にブランチを指定

dict/prh-idiomatic-usage.yml
「続柄マスター」が誤ってエラーと判定されてしまうので、修正したい。
「マスター => マスターデータ」というルールに、ひっかかってしまう。
- ルールの追加
- 特になし
続柄マスターのコード変換は家族情報のみに適用されます
略
=> feat: 「マスター」に関するルール追加

dict/prh-idiomatic-usage.yml
人事評価機能で評価記号マスターがリリースされました。
[評価記号マスターを作成する｜SmartHR](https://support.smarthr.jp/ja/help/articles/0fb112b5-8a16-4c54-a117-870b30079d16/)
「評価記号マスター」が誤ってエラーと判定されてしまうため、エラーとならないよう修正したいです。
「マスター → マスターデータ」のルールに検知されてしまいます。
- ルールの追加
- 特にありません
評価記号マスターは、汎用テンプレートで使用できます。
- 評価マスター
- 記号マスター
=> feat: 「マスター」に関するルールに評価記号マスターを追加
