- CHANGELOG.md
- package.json
> chore: package.json に homepage と repository の記載を追加

- package.json
npmjsへの公開が失敗したので、package.jsonを更新して再度公開の準備をする。
* package.jsonにmeta情報を追加
* `files`のパスを[Stack Overflow](https://stackoverflow.com/questions/27049192/npm-publish-isnt-including-all-my-files)の指摘に合わせて変更
> feat: package.jsonの修正

- CHANGELOG.md
- package.json
> chore(release): 1.3.0

- CHANGELOG.md
- package.json
> chore(release): 1.4.0

- .github/workflows/test.yml
- https://smarthr.atlassian.net/browse/TEXTLINT-21
- Github ActionのPR+push時に`yarn test `, `yarn build`を実行させる
> feat: buildチェック用のGitHub Actionsを追加

- .github/workflows/test.yml
Github Actionsの設定をよりスッキリさせます
* yarn はすでにインストールされているため、 `npm install -g yarn` はやめる
* 1コマンドの実行は1行で書いた
> Github Actionsのconfigで不要な処理を削除する

- yarn.lock
> fix: yarn.lockを再生成

- README.md
https://smarthr.atlassian.net/browse/TEXTLINT-66
READMEの設定サンプルとルール一覧を更新
:pear:
> docs: ja-keishikimeishiに合わせてサンプルやリンク先を変更

- CHANGELOG.md
- package.json
> chore(release): 1.7.1

- .github/workflows/PullRequestAndExportAirtable.yml
- https://kufuinc.slack.com/archives/C01RP2QJT2B/p1645697807346239
- Airtableで出力したコードに異常があってもbuildされてしまう現象を確認した
- `yarn test`コマンドを、`PullRequestAndExportAirtable.yml` に追加した
> chore: airtable書き出し用actionにtestを追加

- example/.textlintrc
- src/index.ts
follow-up https://github.com/kufu/textlint-rule-preset-smarthr/pull/213
- fix indent.
- Disable options as default value.
> fix: follow-up #213

- renovate.json
textlint本体のアップデート方針に合わせ、RenovateでPRをまとめるパッケージを変更したい
renovate.jsonの修正
- textlint本体、textlint-testerをtextlint familyに追加
- @textlint-rule/textlint-rule-no-unmatched-pairをtextlint familyに移動
> feat: RenovateのPRをまとめるパッケージを変更

- CHANGELOG.md
- package.json
> chore(release): v1.17.1

- CHANGELOG.md
- package.json
> chore(release): v1.17.2

- CHANGELOG.md
> chore(release): 1.19.0

- CHANGELOG.md
- package.json
> chore(release): v1.19.0

- renovate.json
> refactor: renovateで古いパッケージを自動でdeduplicateするようにしたい

- dict/prh-idiomatic-usage.yml
「頂(き|く|け)」は[こちら](https://smarthr.design/products/contents/writing-style/#h2-3)のルールで検知できましたが、担当しているプロダクト内で「〇〇頂いて」といったパターンはtextlintで検知できなかったため、活用を追加します。
具体的に追加した活用のルールは以下のとおりです。
```
「頂い」
「頂か」
「頂こ」
```
それぞれ以下のような活用例があります。
例：「頂いて」「頂かせ」「頂こう」等
- 特にありません
1. お送りいただいた通りに進めます。
2. いただかない想定です。
3. いただこうと思います。
1. お送り頂いた通りに進めます。
2. 頂かない想定です。
3. 頂こうと思います。
> feat: 「頂く」の活用を追加

- pnpm-workspace.yaml
npmのサプライチェーン攻撃に対応する
pnpmを使っているので、`minimumReleaseAge`を設定しておく
dependabotは有効にしてないので、dependabotの設定はしていません
🍐
> chore: 最新バージョンのパッケージをインストールを遅らせる

- pnpm-workspace.yaml
推奨値が3日になったので、変更する
値を4320にする
🍐
🍐
> chore: インストールを許容する間隔を3日に変更する
